/** @type {import('tailwindcss').Config} */
export default {
    darkMode: 'class',
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                background: "var(--background)",
                foreground: "var(--foreground)",
                card: "var(--card)",
                "card-foreground": "var(--card-foreground)",
                popover: "var(--popover)",
                "popover-foreground": "var(--popover-foreground)",
                primary: "var(--primary)",
                "primary-foreground": "var(--primary-foreground)",
                secondary: "var(--secondary)",
                "secondary-foreground": "var(--secondary-foreground)",
                muted: "var(--muted)",
                "muted-foreground": "var(--muted-foreground)",
                accent: "var(--accent)",
                "accent-foreground": "var(--accent-foreground)",
                destructive: "var(--destructive)",
                "destructive-foreground": "var(--destructive-foreground)",
                border: "var(--border)",
                input: "var(--input)",
                ring: "var(--ring)",
                // Apple HIG System Colors
                apple: {
                    blue: '#007AFF',
                    green: '#34C759',
                    orange: '#FF9500',
                    red: '#FF3B30',
                    yellow: '#FFCC00',
                    purple: '#AF52DE',
                    teal: '#5AC8FA',
                    gray: '#8E8E93',
                    'gray-2': '#636366',
                    'gray-3': '#48484A',
                    'gray-4': '#3A3A3C',
                    'gray-5': '#2C2C2E',
                    'gray-6': '#1C1C1E',
                },
                // System v3.0 Colors (legacy compat)
                sys: {
                    strategic: "var(--color-strategic)",
                    tactical: "var(--color-tactical)",
                    audit: "var(--color-audit)",
                    general: "var(--color-general)",
                },
            },
            fontFamily: {
                sans: ['-apple-system', 'BlinkMacSystemFont', '"SF Pro Display"', '"SF Pro Text"', 'Inter', '"Helvetica Neue"', 'system-ui', 'sans-serif'],
                mono: ['"SF Mono"', '"Menlo"', '"Monaco"', '"Cascadia Code"', 'monospace'],
            },
            fontSize: {
                'apple-display': ['34px', { lineHeight: '1.15', fontWeight: '700', letterSpacing: '-0.02em' }],
                'apple-title': ['22px', { lineHeight: '1.3', fontWeight: '700', letterSpacing: '-0.01em' }],
                'apple-headline': ['17px', { lineHeight: '1.4', fontWeight: '600' }],
                'apple-body': ['17px', { lineHeight: '1.5', fontWeight: '400' }],
                'apple-callout': ['16px', { lineHeight: '1.4', fontWeight: '400' }],
                'apple-subhead': ['15px', { lineHeight: '1.4', fontWeight: '400' }],
                'apple-footnote': ['13px', { lineHeight: '1.3', fontWeight: '400' }],
                'apple-caption': ['12px', { lineHeight: '1.3', fontWeight: '400' }],
                'apple-caption2': ['11px', { lineHeight: '1.2', fontWeight: '400' }],
            },
            transitionTimingFunction: {
                'apple': 'cubic-bezier(0.25, 0.1, 0.25, 1)',
                'apple-spring': 'cubic-bezier(0.175, 0.885, 0.32, 1.075)',
                'apple-ease': 'cubic-bezier(0.42, 0, 0.58, 1)',
            },
            boxShadow: {
                'apple-sm': '0 1px 3px rgba(0, 0, 0, 0.08), 0 1px 2px rgba(0, 0, 0, 0.06)',
                'apple-md': '0 4px 12px rgba(0, 0, 0, 0.08), 0 2px 4px rgba(0, 0, 0, 0.04)',
                'apple-lg': '0 12px 40px rgba(0, 0, 0, 0.12), 0 4px 12px rgba(0, 0, 0, 0.06)',
                'apple-xl': '0 24px 60px rgba(0, 0, 0, 0.16), 0 8px 20px rgba(0, 0, 0, 0.08)',
                'modal': '0 25px 60px -12px rgba(0, 0, 0, 0.35)',
                // Legacy glass shadows (mapped)
                'glass-1': '0 1px 3px rgba(0, 0, 0, 0.08)',
                'glass-2': '0 4px 12px rgba(0, 0, 0, 0.08)',
                'glass-3': '0 12px 40px rgba(0, 0, 0, 0.12)',
                'neon-cyan': '0 0 6px rgba(0, 122, 255, 0.3)',
                'neon-magenta': '0 0 6px rgba(175, 82, 222, 0.3)',
            },
            borderRadius: {
                lg: "var(--radius)",
                md: "calc(var(--radius) - 2px)",
                sm: "calc(var(--radius) - 4px)",
            },
            keyframes: {
                float: {
                    '0%, 100%': { transform: 'translateY(0)' },
                    '50%': { transform: 'translateY(-6px)' },
                },
                'subtle-pulse': {
                    '0%, 100%': { opacity: 1 },
                    '50%': { opacity: 0.7 },
                },
                'fade-in': {
                    from: { opacity: 0, transform: 'translateY(8px)' },
                    to: { opacity: 1, transform: 'translateY(0)' },
                },
                'pulse-neon': {
                    '0%, 100%': { transform: 'scale(1)', opacity: 1 },
                    '50%': { transform: 'scale(1.05)', opacity: 0.8 },
                },
                blob: {
                    '0%': { transform: 'translate(0, 0) scale(1)' },
                    '33%': { transform: 'translate(15px, -15px) scale(1.05)' },
                    '66%': { transform: 'translate(-10px, 10px) scale(0.98)' },
                    '100%': { transform: 'translate(0, 0) scale(1)' },
                },
            },
            animation: {
                float: 'float 6s ease-in-out infinite',
                'subtle-pulse': 'subtle-pulse 3s ease-in-out infinite',
                'fade-in': 'fade-in 0.4s ease-out',
                'pulse-neon': 'pulse-neon 2.5s ease-in-out infinite',
                blob: 'blob 12s ease-in-out infinite',
            },
        },
    },
    plugins: [],
}
